// Generated by dts-bundle v0.7.3-fork.1
// Dependencies for this module:
//   ../../../../../@fullcalendar/Core

declare module '@fullcalendar/rrule' {
    const _default: import("@fullcalendar/Core").PluginDef;
    export default _default;
}

