// Generated by dts-bundle v0.7.3-fork.1
// Dependencies for this module:
//   ../../../../../@fullcalendar/Core

declare module '@fullcalendar/bootstrap' {
    import { Theme } from '@fullcalendar/Core';
    export class BootstrapTheme extends Theme {
    }
    const _default: import("@fullcalendar/Core").PluginDef;
    export default _default;
}

